### ISSUE TITLE
Bug in Challenge 38 hint

### ISSUE THREAD

**Issue by djvinnie** [OWASP/wrongsecrets#1106]
### What is the expected behavior?
The git fetch command should fetch the git notes correctly.

### What is the actual behavior?
The git fetch command errors out with the following output - fatal: invalid refspec 'refs/notes/:refs/notes/'

### Please provide a reproducible path or test that demonstrates the bug.
Running the currently given git fetch command results in the error

### Any possible solutions?
Running the following command worked for me - `git fetch origin 'refs/notes/*:refs/notes/*'`

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by commjoen** [comment]
Hi @djvinnie looks like it can be fixed by using `git fetch origin "refs/notes/*:refs/notes/*"` want to file apr with an updated solution :) ?

**Comment by djvinnie** [comment]
Sure thing! Please assign the issue to me and I will file a PR to fix the instruction.
