### ISSUE TITLE
Extend terratests to ensure no challenge is disabled in the environment

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#1132]
Currently the Terratests only check the cloud challenges, but there are no checks on whether any challenges are disabled in the home page, while all of the challenges should be enabled. Given https://github.com/OWASP/wrongsecrets/issues/1130 it would be good if we can check that all challenges are usable.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by commjoen** [comment]
The issue is all yours sir!

**Comment by haanhvu** [comment]
@commjoen Hi, AFAIU I need to extend:

- `wrongsecrets_aws_test.go`
- `wrongsecrets_azure_test.go`
- `wrongsecrets_gcp_test.go`

to make sure all challenges are enabled in each cloud platform, right?

**Comment by commjoen** [comment]
Yes👍

**Comment by commjoen** [comment]
for now, isntead of cypress: we need to make sure that no challenge is disabled in the cloud env :) .
