### ISSUE TITLE
Error:  Java: cannot find symbol, symbol: method getFirst(), Location: interface  java.util.List<org.owasp.wrongsecrets.challanges.Challange>

### ISSUE THREAD

**Issue by Shubham-Patel07** [OWASP/wrongsecrets#1150]
### My environment

-   **Operating System**: MacOS Ventura
-   **Java SDK**: Java 21

### Issue

Hi Developers,

I am new to contributing to this organization. After cloning and configuring the repository on my local host, I encountered this error.

<img width="1440" alt="Pasted Graphic" src="https://github.com/OWASP/wrongsecrets/assets/87226371/4fe4c9f0-3605-43b2-82d4-5c4157f7696a">

The Java compiler cannot find the `getFirst()` method for an object that is expected to be of the type java.util.List<org.owasp.wrongsecrets.challenges.Challenge>. This error occurs because the List interface in Java does not have a method named `getFirst()`.

The issue is in `src/main/java/org/owasp/wrongsecrets/challenges/ChallengeUI.java` and `src/main/java/org/owasp/wrongsecrets/challenges/ChallengesController.java`

The reason for this error might be `getFirst()` method is called on `List` object, but such a method is not defined in `LIst` interface. The method is typically for data structures like `LinkedList` or `Deque`. But not for general `List` interface

### Possible solution
To resolve this issue, we can replace the `getFirst()` method call with an appropriate method or alternative that exists in the List interface, such as `list.get(0)`, which will return the first element of the list. 

eg:- in `src/main/java/org/owasp/wrongsecrets/challenges/ChallengesController.java` rather than 

```java
return challenges.getChallenge(challengeDefinition).getFirst().spoiler();
// Line no:100
```
We can use `get(0)` insted of `getFirst()` to get the first element of the object

```java
return challenges.getChallenge(challengeDefinition).get(0).spoiler();
// Line no:100
```

**Comment by commjoen** [comment]
Hi @Shubham-Patel07 , it looks like you might be missing something on your computer:
``` java
    /**
     * {@inheritDoc}
     *
     * @implSpec
     * If this List is not empty, the implementation in this interface returns the result
     * of calling {@code get(0)}. Otherwise, it throws {@code NoSuchElementException}.
     *
     * @throws NoSuchElementException {@inheritDoc}
     * @since 21
     */
    default E getFirst() {
        if (this.isEmpty()) {
            throw new NoSuchElementException();
        } else {
            return this.get(0);
        }
    }
```
is part of Java 21 its List interface. See https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/List.html#getFirst() . Do you use indeed java21? Or is another java version active on your path?

**Comment by Shubham-Patel07** [comment]
<img width="1032" alt="image" src="https://github.com/OWASP/wrongsecrets/assets/87226371/7684530a-f144-4f9a-836b-93bae3becd34">

yes i am indeed using java 21.

I think, getFirst() method cannot be found for the type returned by `challenges.getChallenge(challengeDefinition)`. getFirst() method is typically associated with data structures like LinkedList, and it seems that the getChallenge() method does not return a `List` or `LinkedList`

**Comment by commjoen** [comment]
@Shubham-Patel07 I am afraid the problem is local to your setup as this is working code already released at https://wrongsecrets.herokuapp.com/. and runs in the unit tests in our runners (see https://github.com/OWASP/wrongsecrets/actions/workflows/main.yml ) 
We are using eclipse temurin with java features set to 21:
<img width="909" alt="image" src="https://github.com/OWASP/wrongsecrets/assets/1457214/37105e21-a47d-42cf-a95e-1790f56b7071">
Hope that helps! Otherwise, I am afraid i cannot really help you here. Maybe try out our Slack support channels?

**Comment by commjoen** [comment]
A `List<Challenge>` Is a typed List which still has `getFirst()` as a method . In that case the typed list returns the first not null entry of that type (E.g. Challenge).

**Comment by Shubham-Patel07** [comment]
Thanks @commjoen !!

I am currently a final-year student pursuing a Bachelor's degree in Computer Science and Engineering. Upon reviewing the OWASP/wrongsecrets repository, I found that the project aligns well with my technical expertise and interests.

I am eager to contribute to the OWASP/wrongsecrets project and would greatly appreciate any guidance you can provide on how to get started. Your advice on the initial steps and how I can effectively participate in the project would be invaluable.

**Comment by commjoen** [comment]
Please have a look at the readme and contributing pages in order to move forward.
