### ISSUE TITLE
Format Python scripts using Black

### ISSUE THREAD

**Issue by za** [OWASP/wrongsecrets#1200]
Hi there,

What if we format the Python scripts `scripts/sort_contibutors/main.py` using [Black](https://github.com/psf/black)? The goal of formatting is to increase readability of the code (as we follow the standardized format on writing the code).

If OK, I'll create a PR for this. So far, I only found one Python script on this repo.

**Comment by commjoen** [comment]
Hi @za ,
I am fine if you format imports/code, but can you please add any formatter to the pre-commit hooks? Note: the pre-commit hooks need to run on windows/linux and primarily on MacOS.

**Comment by za** [comment]
OK, will have a look on the pre-commit part @commjoen

**Comment by za** [comment]
Thanks for the review @commjoen !
