### ISSUE TITLE
Document: Add ACM or Let's encrypt support for ALB setup in AWS

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#149]
Currently we support using an ALB which still is over HTTP. It would be great if we can add scripts to secure the connection using SSL based on public AWS ACM or Lets' encrypt CAs (or any other of your liking :D )

**Comment by tiborhercz** [comment]
I have looked into this, If we want to add a certificate to the load-balancer we need to add a DNS name/domain name. Which for a temporary installed project like this is not preferred to add a temporary domain name.

**Comment by commjoen** [comment]
hmm i woudl not know any alternative to be honest...so fine by me for now :D

**Comment by bendehaan** [comment]
Okay, how about the following: we use Let's encrypt (doesn't require a custom domain), and a network load balancer. The NLB allows TLS passthrough, so that might work

**Comment by commjoen** [comment]
Given there are quite a few options again, we decided to extend the AWS README instead.

**Comment by commjoen** [comment]
Closed in https://github.com/OWASP/wrongsecrets/pull/1407
