### ISSUE TITLE
Migrate tfsec to trivy

### ISSUE THREAD

**Issue by bendehaan** [OWASP/wrongsecrets#1764]
### What is the actual behavior?

Tfsec warns that it is no longer updated but lives on as part of Trivy.

### Any possible solutions?

Migrate to [trivy](https://github.com/aquasecurity/trivy) using the [migration guide](https://github.com/aquasecurity/tfsec/blob/master/tfsec-to-trivy-migration-guide.md)

### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by za** [comment]
I am initiating a PR. Please have a look. cc: @commjoen
