### ISSUE TITLE
write and publish detection rules for open source tools in a separate repo

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#329]
- [ ] get a repo organized with github actions, etc.. 
- [ ] pick up the first secret from the testbed (https://github.com/commjoen/wrongsecrets/issues/201) to write rules/config for for both tools. best would be to take one you are very familiar with from the list in that issue (e.g. you can smell/recognize the credential for miles away :smile: )
- [ ] setup a test suite to see if the tool(git-secrets/trufflehog/detect-secrets) using the rule detects exactly that and not too much  (e.g. very low false positive ratio)
- [ ] make sure we have a github action to fire the rule suite, linters, etc.
- [ ] rinse and repeat for other secrets in testbed (e.g. create rules and detection tests, with possible separate issues in another git repo)

**Comment by commjoen** [comment]
this could be for https://github.com/Yelp/detect-secrets as well aaaand we might need base64 encoded/ hex encoding stuff as well?

**Comment by mackowski** [comment]
I will help with that

**Comment by MrLucif3r** [comment]
I am in for contribution.

**Comment by Muska12345** [comment]
I am up for the task

**Comment by commjoen** [comment]
Awesome! Assigned it to all 3 of you :) welcome to the team!

**Comment by commjoen** [comment]
Decisions to be tackled:
- [ ] one tool (if so which?) versus all 3 tools in scope of this issue
- [ ] any other tool to extend?
- [ ] repos: commjoen, wrongsecrets-orga, owasp (prefered wrongsecrets-orga for now)

**Comment by commjoen** [comment]
Given nothign really came out of this, I am closing this issue and generating a new one with fresh assisgnment slot and hacktoberfest possibility.
