### ISSUE TITLE
Various github instruction secret challenges

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#423]
- [x] Have a Github wiki instruction secret as per the Stammtich Hamburg meetup: we should have a secret in the wiki as part of an "instruction" or "example" . 

@w1ntermute mentioned next to this one: 

- [x] a secret in a closed github issue ^^.
@drwetter mentioned: An edited github issue where one realized that he pasted some secret sauce in by accident and then edit it to remove it.
- [x] have a screenshot in an issue (CloseD) to have the secret inside accidentaly "my passphrase is broken" and show the pahssphrase in the screenshot for a GPG/RSA key unlock action.

**Comment by MaSven** [comment]
The text could

#We need to rotate our AWS credentials
The security said we need to rotate our secrets every 3 Months. So in this ticket we want to rotate the AWS Accesskeys. We also need to remove the old one without disruption.
- [ ] Create new keys
- [ ] Input the new keys
- [ ] Deployment
- [ ] Wait till the old keys are not used for a day
- [ ] deactivate the old keys
- [ ] delete the old keys

I don't have the permissions to create tokens Person2 can you do it?

Person2 Comment:
Yes I can.
Here are the new credentials aws_access_key: enoefnenfen
aws_secret_key: eoioiefoifoiefon

Comment2:
Thank you. Now we are safe again!
Close Ticket

**Comment by puneeth072003** [comment]
@commjoen Happy to help.....please assign this work to me.

**Comment by commjoen** [comment]
Hi @puneeth072003 , have a go at it!

**Comment by commjoen** [comment]
@puneeth072003, are you on OWASP slack?

**Comment by puneeth072003** [comment]
@commjoen No, 
Sorry I'm a newbie here i need help in getting started, please can you guide me

**Comment by puneeth072003** [comment]
@commjoen where can i start

**Comment by commjoen** [comment]
As discussed over Slack: CONTRIBUTING.md and README should help you along the way. Feel free to DM over slack when you are stuck.

**Comment by puneeth072003** [comment]
Sure

**Comment by puneeth072003** [comment]
@commjoen Ok.
