### ISSUE TITLE
Migrate and centralize wrongsecrets into the OWASP Github organization

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#453]
In order to ease collaboration and not make it "the personal pet project of Jeroen Willemsen", I would like to migrate everything to the OWASP organization. This should help to get "production" status as well and attract new people to provide input/challenges.
Tasks at hand are:
- [x] Add @hblankenship to all repoes.
- [x] move wrongsecrets, wrongsecrets-ctf-party, and wrongsecrets-binariers into https://github.com/owasp by @hblankenship (added as collaborator)
- [x] update all references to the new github links in wrongsecrets
- [x] update all references to the new github links in wrongsecrets-ctf-party
- [x] update all references to the new github links in wrongsecrets-binaries
- [x] Update the www-repository of OWASP.
- [x] Update Docker hub repo pages
- [x] Create a new release
- [x] Advertise the change through linkedin and twitter
- [x] Create some sort of blog on https://dev.to/commjoen to explain why we want to move. (https://dev.to/commjoen/why-wrongsecrets-moved-to-the-owasp-github-organization-16om) 
- [x] Update slack channel
- [x] Inform twitter (Kubespsloit, https://www.kitploit.com/2022/05/wrongsecrets-examples-with-how-to-not.html, greyhats)

**Comment by commjoen** [comment]
It seems that OWASP directives require us to migrate to OWASP repos. We will have a check in on this in a few weeks when we have more time to think about how that affects everything :) .

**Comment by curphey** [comment]
It should def be moved into the OWASP org IMO. You will get a better pick up from the community. If I am elected to the board all OWASP projects will have be in the OWASP org ;-)

**Comment by commjoen** [comment]
Updated ticket with the right steps, now checking in with the OWASP project director on what needs to be done next.
