### ISSUE TITLE
Choose another license

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#494]
In order to make sure that no one tries to monetize this platform , we will have to find another license.
Maybe https://github.com/OWASP/owasp-mastg/blob/master/License.md ? 

This can help people to feel better protected in their spare time efforts they put in this project.

**Comment by commjoen** [comment]
1 option: Attribution-ShareAlike 4.0 International

**Comment by commjoen** [comment]
https://twitter.com/commjoenie/status/1590431607978356737?s=20&t=qalF5Cam_uBQ95IaxNPOrg

**Comment by commjoen** [comment]
We might choose AGPL instead https://choosealicense.com/licenses/agpl-3.0/

**Comment by Jeymz** [comment]
I think AGPL 3.0 would make sense here. Being a copy left license it would require any organization that uses this to make available their source. But I'm not sure it would prevent monetization of the project.

**Questions:**
- Is your concern that companies would leverage this platform as a paid SAAS CTF Solution?
- Is there a specific scenario you are attempting to prevent? 

**References:** 
- [Quora Question / Answer](https://www.quora.com/Is-there-an-open-source-license-that-prevents-anyone-from-selling-my-software) 
- [Tech Republic Article](https://www.techrepublic.com/article/dont-believe-the-hype-agpl-open-source-licensing-is-toxic-and-unpopular/)
