### ISSUE TITLE
Replace depreciated Asciidoctor::convert() used in AsciiDocGenerator

### ISSUE THREAD

**Issue by MarcinNowak-codes** [OWASP/wrongsecrets#525]
As a developer I want not to use new recommended API instead of old depreciated API for `Asciidoctor::convert()` and `OptionsBuilder::options()` from `org.asciidoctor` 2.5.7 package.

*Acceptance criteria:*
- All use of `Asciidoctor::convert()` is replaced with recommended bean configuration
- All use of `OptionsBuilder::options()` is replaced with recommended bean configuration.

**Comment by nhumblot** [comment]
Hi :wave: 

I started to work on this one, is it possible to assign it to me? Thank you! :slightly_smiling_face:

**Comment by commjoen** [comment]
Floor is yours good sir!
