### ISSUE TITLE
Implement GraalVM support

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#530]
Now that we are on spring boot 3: it would be nice to test if we can already use GraalVM with our current set of libs: https://betterprogramming.pub/going-native-with-spring-boot-3-ga-4e8d91ab21d3

**Comment by bendehaan** [comment]
Played with this for bit, Liberica native image kit does not support JDK19 yet. Need to wait for a bit. https://bell-sw.com/pages/downloads/native-image-kit/

**Comment by commjoen** [comment]
Hi @bendehaan do you have any update on this :) ?

**Comment by bendehaan** [comment]
@commjoen still blocked for now due to Azure sdk

**Comment by commjoen** [comment]
GraalVM gives us some performance, but at the cost of a lot of upgrade issues. We will close this issue now.
