### ISSUE TITLE
Small error in the Readme.md file

### ISSUE THREAD

**Issue by puneeth072003** [OWASP/wrongsecrets#553]
![Screenshot 2022-12-28 200053](https://user-images.githubusercontent.com/119479391/209827633-1600e296-2a20-490e-b6ff-16278dba6985.png)
Is this supposed to be like this or there is a mistake here.
Happy to create a PR correcting this issue

**Comment by puneeth072003** [comment]
![Screenshot 2022-12-28 201522](https://user-images.githubusercontent.com/119479391/209829388-63f6b8cd-f571-45d7-8c77-473a90ad8760.png)
found another one

**Comment by bendehaan** [comment]
hi @puneeth072003, the first one is supposed to be like that indeed. Addressed the other one in #554.

**Comment by puneeth072003** [comment]
@bendehaan Ahh, I wanted to fix that, i was just clarifying:)
missed a great chance:(

**Comment by puneeth072003** [comment]
@bendehaan Sorry since I'm a beginner i couldn't do that soon.

**Comment by puneeth072003** [comment]
@bendehaan Please do let me know if those kind of beginner friendly issues occur, Happy to fix those.
