### ISSUE TITLE
Creating Pictorial Step by Step guide

### ISSUE THREAD

**Issue by puneeth072003** [OWASP/wrongsecrets#558]
Shall I create a pictorial step by step for this part so that project will be more beginner friendly and encourage more and more contributions from young community.
                  Being a newbie in open Source, I can understand the problem we face, hope you can understand:)
![Screenshot 2022-12-31 063000](https://user-images.githubusercontent.com/119479391/210120407-ba5a5dc8-de6e-4de6-ab56-2600b77bf054.png)

**Comment by puneeth072003** [comment]
More than happy to help in this work.😊

**Comment by commjoen** [comment]
Yes please 🙏! That’s awesome! Can you put the images in https://github.com/OWASP/wrongsecrets/tree/master/images please?

**Comment by puneeth072003** [comment]
> 

More than happy to help......Thank you for assigning issue to me:-)

**Comment by puneeth072003** [comment]
@commjoen Ok I'll start working on it.

**Comment by puneeth072003** [comment]
### Sucessfully Completed.
you can see it as BeginnerGuide.Md

**Comment by puneeth072003** [comment]
@commjoen Anything missing.

**Comment by commjoen** [comment]
The branch is not integrated into our master yet ;) , please create a PR towards the master of this repo, so we can review ;-) .

**Comment by puneeth072003** [comment]
@commjoen Ok sir ;-)

**Comment by commjoen** [comment]
Done in https://github.com/OWASP/wrongsecrets/pull/653
