### ISSUE TITLE
Report of few broken links.

### ISSUE THREAD

**Issue by puneeth072003** [OWASP/wrongsecrets#568]
Guys it seems these links are broken:-)
![gitreport](https://user-images.githubusercontent.com/119479391/210956522-77902e23-8655-4319-abcd-11472def9970.png)
##############################################################################################
![gitreprt](https://user-images.githubusercontent.com/119479391/210956530-d503af86-c272-43d1-968a-d4b505575c8a.png)

**Comment by commjoen** [comment]
Hi @puneeth072003 ! These are 2 different containers exposed at different places. Closing this.
