### ISSUE TITLE
 Windows is not supported.

### ISSUE THREAD

**Issue by puneeth072003** [OWASP/wrongsecrets#569]
# Here's my error
[ERROR] Failures:
[ERROR]   Challenge19Test.spoilerShouldNotCrash:22
Expecting actual:
  Spoiler[solution=Error with executing]
not to be equal to:
  Spoiler[solution=Error with executing]
[ERROR]   Challenge20Test.spoilerShouldNotCrash:21
Expecting actual:
  Spoiler[solution=Error with executing]
not to be equal to:
  Spoiler[solution=Error with executing]
[ERROR]   Challenge21Test.spoilerShouldNotCrash:21
Expecting actual:
  Spoiler[solution=Error with executing]
not to be equal to:
  Spoiler[solution=Error with executing]
[ERROR]   Challenge22Test.spoilerShouldNotCrash:21
Expecting actual:
  Spoiler[solution=Error with executing]
not to be equal to:
  Spoiler[solution=Error with executing]
[INFO]
[ERROR] Tests run: 102, Failures: 4, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:45 min
[INFO] Finished at: 2023-01-12T05:03:52+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project wrongsecrets: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Shamanth\Documents\GitHub\wrongsecrets\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-19\bin\java" -jar C:\Users\Shamanth\AppData\Local\Temp\surefire9245886621137930443\surefirebooter9897
96737777250202.jar C:\Users\Shamanth\AppData\Local\Temp\surefire9245886621137930443 2023-01-12T04-59-30_207-jvmRun1 surefire12683119814621391953tmp surefire_024804
13767616161084tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.owasp.wrongsecrets.SecretsErrorControllerTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-19\bin\java" -jar C:\Users\Shamanth\AppData\Local\Temp\surefire9245886621137930443\surefirebooter9897
96737777250202.jar C:\Users\Shamanth\AppData\Local\Temp\surefire9245886621137930443 2023-01-12T04-59-30_207-jvmRun1 surefire12683119814621391953tmp surefire_024804
13767616161084tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.owasp.wrongsecrets.SecretsErrorControllerTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1]

**Comment by commjoen** [comment]
Good point @puneeth072003 ! Till now we did not consider windows, but only a few linux/mac os variants on X86-64 and ARM :) ... let's see if we can get it crosscompiled to work on Windows as well :)

**Comment by commjoen** [comment]
For this we have 2 actions:

- [ ] for every binary: have cross compilation: https://github.com/OWASP/wrongsecrets-binaries/issues/5 
- [ ] for every challenge: implement additional windows detection in the helper & challenge to detect the windows OS and select the-for-windows-cross-compiled-binary

**Comment by commjoen** [comment]
<img width="1748" alt="Screenshot working tests" src="https://user-images.githubusercontent.com/1457214/213098113-3d5baf0a-31b8-4137-bc6e-df80293ca6e5.png">
<img width="1748" alt="Screenshot working app" src="https://user-images.githubusercontent.com/1457214/213098115-dc985a8c-acc4-4da4-a317-c46d192c6a26.png">

Hi there, 
as per virtual machine test: the app and tests work from IntelliJ community edition with Windows 10, JD19 & Node18.
