### ISSUE TITLE
Leave a secret in git notes

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#614]
- [ ] Branch and hide your secret via https://git-scm.com/docs/git-notes
- [ ] Encrypt the secret similar like our other challenges
- [ ] Create the challenge itself explaining how a dev tried to use https://git-scm.com/docs/git-notes to hide a secret.

**Comment by RemakingEden** [comment]
Am I good to take this?

**Comment by commjoen** [comment]
For now: https://github.com/RemakingEden/git-notes-research is being worked on, based on these results the challenge can(not) continue and/or articles will be published and linked to the projects site and readme.
