### ISSUE TITLE
New Challenge: Leave a secret somewhere in Reddit by “mistake”

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#616]
This challenge is about educating users of the fact that secrets can be leaked through social media.
TODO's;
- [x] Create a new challenge about how microsoft made a mistake with https://www.wired.co.uk/article/microsoft-handed-the-keys-to-almost-every-windows-10-installation-over-to-hackers and that something similar happened here
- [x] Have the key in a Reddit post somewhere to simulate the issue
- [x] Create a new challenge according to contributing.md and eencrypt the challenge its answer/key properly in the javacode

**Comment by santimoy044** [comment]
I shall try to lead this.

**Comment by bendehaan** [comment]
@santimoy044 perfect, thanks!

**Comment by santimoy044** [comment]
My pleasure

**Comment by bendehaan** [comment]
@santimoy044 how's it going? Any updates on your progress? We're considering giving this issue to someone else, but if you're busy and have put some work in already, we'll leave it for you.

**Comment by divyanshuagarwal-23** [comment]
Hello @commjoen I am a new contributor
want to take this up
please assign this to me

I had few questions:
1. How to create a new challenge
2. Can you share the code base
3. Is the Reddit post going to be public, if yes how is ur code reading it
4. How to encrypt the password
5. Are we going to leak the encrypted password or decyprted password through Reddit

**Comment by commjoen** [comment]
We will reassign this issue in case there is no response within a week :-)

**Comment by divyanshuagarwal-23** [comment]
sure @commjoen 
let me check thank you

**Comment by djvinnie** [comment]
Can I please get this issue assigned to me? Looks like it has been idle for some time now.

**Comment by commjoen** [comment]
it is yours now ;)

**Comment by djvinnie** [comment]
Thank you :)
I do have one question - Is there any particular subreddit where the secret should be posted? And do I post the secret from my own reddit account?

**Comment by commjoen** [comment]
Any reddit is fine really, as long as it is approved tyoe of content. You can post it with your own account, we don't manage any wrongsecrets reddit account.
