### ISSUE TITLE
Docker image jeroenwillemsen/wrongsecrets:1.5.14-no-vault hangs on Colima container runtimes on macOS with M1

### ISSUE THREAD

**Issue by MarcinNowak-codes** [OWASP/wrongsecrets#630]
Precondition:
- macOS Ventura with Apple M1 CPU
- [Colima](https://github.com/abiosoft/colima) installed
- Colima is default Docker context

When run command in the terminal:
```
docker run --rm -p 8080:8080  jeroenwillemsen/wrongsecrets:latest-no-vault
```
the container boots up very slow or event hangs.

**Comment by commjoen** [comment]
Thank you for filing the issue good sir! Similar to podman and running things directly on Windows: I cannot support maintenance of this on the long run... So can I ask a favor when you find a solution good sir?
Would you be so kind to create "experimental instructions" on how to make it work?

**Comment by commjoen** [comment]
New idea: could you please create a GitHub action triggered on merge requests that checks if docker containers work on podman , Docker and Colima?

**Comment by commjoen** [comment]
Automated tests for colima and for podman added at https://github.com/OWASP/wrongsecrets/pull/651 :) can you please review :) ?

**Comment by commjoen** [comment]
Do you have any update on this @MarcinNowak-codes ?
