### ISSUE TITLE
New challenge: save a secret in FrontEnd localStorage in browser

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#648]
Let's store a secret in LocalStorage and explain why you should use any storage but that to have secrets with examples

**Comment by Novice-expert** [comment]
Please assign this to me, I'm interested in this.

**Comment by commjoen** [comment]
@Novice-expert the issue is all yours! Have a lot of fun developing it!

**Comment by Novice-expert** [comment]
Sir, I have a doubt, Here we are talking about HTML DOM Window localStorage right? Which allows us to store data as key-value pairs in our web browser using an object.

**Comment by commjoen** [comment]
Yes :-). So the idea is to generate a hard to guess/reverse engineer secret and put it in the LocalStorage

**Comment by commjoen** [comment]
soooo, my recommendation would be;
1. have a look at other challenges how we interact with the front-end there
2. have a look at challenges where we, in the backend, generate random values at startup
3. now create a thymeleaf templated javascript that drops the secret in LocalStorage
4. add the required documentation & tests
