### ISSUE TITLE
Create a Table of Contents in the Readme

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#666]
### What do you think about adding Table of Contents to readme file since it is very long and hard to navigate through😃

_Originally posted by @puneeth072003 in https://github.com/OWASP/wrongsecrets/discussions/587_

**Comment by commjoen** [comment]
Assigned to @puneeth072003 (pending github invite)

**Comment by puneeth072003** [comment]
@commjoen I was just about to create a new issue regarding that...sure

**Comment by AkankshaAI** [comment]
@commjoen I would like to contribute and resolve this issue , I assure you completing  as soon as possible. Please assign me the task

**Comment by commjoen** [comment]
> @commjoen I would like to contribute and resolve this issue , I assure you completing as soon as possible. Please assign me the task

See #668 : @puneeth072003 has almost completed it already.

**Comment by commjoen** [comment]
@AkankshaAI if you want to find a good issue to work at, feel free to contact us via OWASP Slack :), so we can figure out something that fits you :).

**Comment by AkankshaAI** [comment]
> @AkankshaAI if you want to find a good issue to work at, feel free to contact us via OWASP Slack :), so we can figure out something that fits you :).

Sure , thank you so much for the information.
