### ISSUE TITLE
Unintened Switching of Themes in WebServer

### ISSUE THREAD

**Issue by puneeth072003** [OWASP/wrongsecrets#673]
### Description
It seems our web server's default theme is set to dark but whenever I set my theme to **light** and then enter a challenge the theme switches back to **dark**.

### What is the expected behavior?
To continue with the white theme.

### What is the actual behavior?
It switched me back to the Dark theme.

### Is the bug confirmed?
**Yes** (By @commjoen )

### Related images
![Screenshot 2023-03-08 054842](https://user-images.githubusercontent.com/119479391/223735593-af1c8429-5612-415b-9c86-9ad261b842f9.png)

![Screenshot 2023-03-08 052550](https://user-images.githubusercontent.com/119479391/223735823-b67f50ff-1d0f-4e1a-b907-895f07e71869.png)

**Comment by turjoc120** [comment]
Hi, I want to help on resolving it

**Comment by commjoen** [comment]
@turjoc120 , the challenge is all yours! I think we need to persist the users choice in a cookie :D
