### ISSUE TITLE
Use PBKDF2 with SHA-256 on a stable static defined password ;-)

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#692]
### Context
In this scenario people just want to create a random key, but forget that they are using a stable input. 
So: can you find the actual key?
The participant should learn that hardcoded seeds of a key with deterministic functions like PBKDF2, will not help you at all to create a protected key.
The category would be Docker.

### Did you encounter this in real life? Could you tell us more about the scenario?

I encountered this scenario twice now: once a hardcoded key in code, once an ENV var was used as a seed.

**Comment by Rupesh528** [comment]
Certainly! In this scenario, the participants were attempting to create a random key for use in Docker, but they made the mistake of using a stable input as the seed for generating the key. Specifically, they either hard-coded the seed into their code or used an environment variable as the seed.

In the case of Docker, it is recommended to use Docker secrets to securely store sensitive information such as keys and passwords. This can help to prevent accidental exposure of sensitive information and provide an additional layer of security. Additionally, it is important to regularly review and update security practices to ensure that sensitive information remains protected.

**Comment by commjoen** [comment]
hi @Rupesh528 , do you want to implement the challenge :) ?

**Comment by commjoen** [comment]
Let's use https://www.dcode.fr/pbkdf2-hash as part of the solution :)
