### ISSUE TITLE
Rotate our AWS credentials

### ISSUE THREAD

**Issue by puneeth072003** [OWASP/wrongsecrets#694]
## We need to rotate our AWS credentials
The security said we need to rotate our secrets every 3 Months. So in this ticket we want to rotate the AWS Accesskeys. We also need to remove the old one without disruption.

- [ ] Create new keys
- [ ] Input the new keys
- [ ] Deployment
- [ ] Wait till the old keys are not used for a day
- [ ] deactivate the old keys
- [ ] delete the old keys

I don't have the permissions to create tokens @commjoen  can you do it?

**Comment by commjoen** [comment]
Your Comment:
Yes I can.
Here are the new credentials aws_access_key: enoefnenfen
aws_secret_key: asdfdpuYUIadbaoasdpa07kj2003

**Comment by puneeth072003** [comment]
### Thank you. Now we are safe again!
**Close ticket.**
