### ISSUE TITLE
Request credits with cloud providers to cut costs

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#695]
- [x] Request AWS credits:https://opensourcecreditsapplicationform.s3.us-east-2.amazonaws.com/AWS+Open+Source+Credits+Application+Form.xlsx 
- [x] Request azure credits: https://opensource.microsoft.com/azure-credits/#credits-overview

**Comment by bendehaan** [comment]
Applied for Azure credits: decision in 3-4 weeks.

**Comment by bendehaan** [comment]
[AWS estimate](https://calculator.aws/#/estimate?id=1a654591adb485ae16644d2f39db5923a97434f0). Application sent, reviewed every month. Note that this is a 1-year credit sponsorship.

**Comment by bendehaan** [comment]
AWS replied: answer within 30 days.

**Comment by commjoen** [comment]
AWS done, now awaiting azure so we can close this ;-)

**Comment by commjoen** [comment]
Azure did not respond. however: OWASP is getting credits centrally, closing this down.
