### ISSUE TITLE
Add devcontainer

### ISSUE THREAD

**Issue by bendehaan** [OWASP/wrongsecrets#702]
### Context

Setting up the project dependencies can be a hassle, especially for newcomers. We want a reusable devcontainer such that people new to the project get a jump start, and people already working on the project do so in a reproducible way.

- [VS Code supports this natively](https://code.visualstudio.com/docs/devcontainers/create-dev-container)
- [For IntelliJ it's on the roadmap](https://youtrack.jetbrains.com/issue/IDEA-202267)

### Alternatives

- Webtop: requires a lot of maintenance, and doesn't offer a nice dev experience.
- Regular docker images: more time to set up and maintain. Doesn't have the nicest dev integrations like VS Code has.

### Has the feature been requested before?

No

### If the feature request is approved, would you be willing to submit a PR?

Yes, but if the community wants to pick this up they're more than welcome as well :)

**Comment by commjoen** [comment]
Hi @bendehaan do you have any updates on this?

**Comment by bendehaan** [comment]
@commjoen just looked into it, seems this is supported by IntelliJ now, I'd say remove the blocked label and I'll have a go!

https://www.jetbrains.com/help/idea/connect-to-devcontainer.html#create_dev_container_inside_ide

**Comment by za** [comment]
Hi, can I take this issue? 

Note: I don't have IntelliJ and no prior experience with devcontainer.

**Comment by commjoen** [comment]
@za , I just talked to @bendehaan on slack and we are happy if you want to give this a go :) .

**Comment by bendehaan** [comment]
Closing - discussed during NLUUG, don't think it's worth the effort at this time. Further PRs with implementations are welcome, however!
