### ISSUE TITLE
Add misconfiguration of docker secret in code (See for docker compose: https://docs.docker.com/engine/swarm/secrets/)

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#811]
Create a challenge for docker compose setup, where the compose secret is hardcoded inside teh docker compose yml

TODO:
- [x] Implement a docker-compose setup for wrongsecrets with the secret as an env var, add the compose file to the repo
- [x] implement the challenge according to contributing.md, but make sure we read the challenge from the file so we can play the challenge without the need to actually use teh docker-compose setup.

**Comment by Shubham-Patel07** [comment]
HI @commjoen,
I want to work on this issue Please assign this one to me 😁

**Comment by commjoen** [comment]
it;s all yours :D .

**Comment by commjoen** [comment]
note: the docker-compose file and its env should only be used to showcase that the problem is real ;-), we should just make it work from a docker perspective. 
The .env file will have to be copied into the container to "Fake" it i guess. (And we need to explain in the code as a doc why we do it)
