### ISSUE TITLE
Add home screen UI tests

### ISSUE THREAD

**Issue by RemakingEden** [OWASP/wrongsecrets#826]
### Context

We are missing some home screen tests. The challenges tests interact with the home page but thinking about it, all the challenge tests that start on the home page should probably be in a home page pack of tests. On top of that we could add:

- Search tests
- Pagination tests (Both the page switcher and the amount of challenges shown on the screen)
- All the navigation buttons
- Any internal links on the home screen (the vault secret etc)
- The table sorting

**Comment by commjoen** [comment]
Sounds like a plan, though it does feel a bit that we are testing a widget integration :). If you want ot: please go for it :)

**Comment by RemakingEden** [comment]
> Sounds like a plan, though it does feel a bit that we are testing a widget integration :). If you want ot: please go for it :) 
What do you mean by this? Are the table elements just a pre built widget?

**Comment by commjoen** [comment]
yes :) https://datatables.net/examples/styling/bootstrap5.html

**Comment by RemakingEden** [comment]
Okay yeah thats a good shout. We don't want to add un needed time to these tests. I will close this unless more is added to the homepage at a later date.
