### ISSUE TITLE
Make "Star"ing steps for the repo more clear in the app

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#968]
### Context

Clicking hte "star us" button does not add a star yet: people still have to click the "star" button to give this repo a star.
We need to find a way on how to make that clear.

### Alternatives

- add some text on what to be done to start repo below the button
- add a popup when you click the button with instructions

### Has the feature been requested before?

No

### If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by djvinnie** [comment]
I would like to take up this issue please!

**Comment by commjoen** [comment]
Fixed in https://github.com/OWASP/wrongsecrets/pull/980
