### ISSUE TITLE
Revise contributor rankings

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#984]
Everyone is a top-contributor now, which does not discern folks who did a lot more than others.
Let's revise this and have top and normal contributors.
Top-contributor: additions above 1000 in git (including ctf-party and binaries repo :D )
Contributor; anything above 0.
Idea would be to automate this with a script which can run on MacOS and Linux and should have the following steps:

- [ ]  enumerate the amount of contributions per user found in [wrongsecrets](https://github.com/OWASP/wrongsecrets)/[wrongsecrets-ctf-party](https://github.com/OWASP/wrongsecrets-ctf-party)/[wrongsecrets-binaries](https://github.com/OWASP/wrongsecrets-binaries)
- [ ]  for every user that has more commits than 100: add to top-contributor, otherwise add to contributor
- [ ]  add "Special thanks" and "tester" listing as hardcoded part of the script
- [ ]  based on the above: generate a markdown and html overview that can replace current snippets in readme.md and [welcome.html](https://github.com/OWASP/wrongsecrets/blob/master/src/main/resources/templates/welcome.html).

**Comment by commjoen** [comment]
Idea would be to automate this with a script:
- [ ] enumerate the amount of contributiosn per user found in wrongsecrets/wrongsecrets-ctf-party/wrongsecrets-binaries
- [ ] for every user that has more commits than 250: add to top-contributor, otherwise add to contributor
- [ ] add "Special thanks" and "tester" listing as hardcoded part of teh script
- [ ] based on the above: generate a markdown and html overview that can replace current snippets in readme.md and home.html.

**Comment by commjoen** [comment]
Will create something based on https://github.com/commjoen/contributors-mstg/blob/master/contrib_generator.py

**Comment by commjoen** [comment]
This task is free for anyone to pickup ;-)

**Comment by roddas** [comment]
I'm working on it, assign me please.
